### ISSUE TITLE
Authentication no longer works

### ISSUE THREAD

**Issue by zachberger** [grocky/go-instacart-export#1]
The call on [instacartApi.go#L33](https://github.com/grocky/go-instacart-export/blob/main/instacartApi.go#L33) returns  `{"error":{"message":"Unauthorized"},"meta":{"triggered_action":null}}` even when specifying a valid cookie. It looks like a CSRF token is now needed.

**Comment by grocky** [comment]
This is now fixed in v0.2.0. They changed the session cookie name to `_instacart_session_id`.
